### PR TITLE
fix legacy start/end ranges, fixes #97

### LINKED ISSUE #97: Legacy start/end return wrong results when reverse:true
Follow-up to #96. I discovered some cases where the legacy `start`/`end` options don't work if you include `reverse`. I have a failing test, and I'll also attempt to fix.

### PR DESCRIPTION
**Pull request by nolanlawson**
Adds a test to reproduce the start/end/reverse error, and fixes it.
The test fails before the fix, but succeeds after.

BTW I wasn't really sure whether you consider this a bug in `ltgt.toLtgt`
or in this module, but now that you have a failing test, it's your call. :)

Basic issue is that `ltgt.toLtgt()` was leaving in the old `start`/`end`
values, which then ended up confusing the range logic in this
module later on down the line.

### CODE REVIEW

File: nut.js [hunk 1]
```diff
@@ -164,6 +164,10 @@ module.exports = function (db, precodec, codec, compare) {
 
       ltgt.toLtgt(opts, opts, encodeKey, precodec.lowerBound, precodec.upperBound)
 
+      // if these legacy values are in the options, remove them
+      delete opts.start
+      delete opts.end
+
```
Comment (nolanlawson) [inline nut.js]: ^ this is the thing that I dunno whether you want to do in `ltgt` or in this module

File: range.js [hunk 2]
```diff
@@ -79,14 +79,6 @@ function addPrefix(prefix, range) {
...
   if(has(range, 'lte')) r.lte = [prefix, range.lte]
   if(has(range, 'gte')) r.gte = [prefix, range.gte]
-  if(has(range, 'start')) {
-    if(range.reverse)  r.lte = [prefix, range.start]
-    else               r.gte = [prefix, range.start]
-  }
-  if(has(range, 'end')) {
-    if(range.reverse)  r.gte = [prefix, range.end]
-    else               r.lte = [prefix, range.end]
-  }
```
Comment (nolanlawson) [inline range.js]: ^ no longer needed since we migrate old opts to the new style

File: test/legacy-start-end.js [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+      if (++i === testCases.length) {
+        return t.end()
+      }
+      var testCase = testCases[i]
+      testRange(testCase[0], testCase[1], t, next)
+    }
+
+    next()
+  })
+})
```
Comment (nolanlawson) [inline test/legacy-start-end.js]: For the record, you can run these tests on `db` instead of `sub` to verify what leveldown does vs what this module does. leveldown passes all these tests without any changes.

Comment (juliangruber) [inline test/legacy-start-end.js]: maybe iterate over `[db, sublevel(db)]` to prove both behave the same

Comment (nolanlawson) [inline test/legacy-start-end.js]: good idea! will do

Comment (nolanlawson) [inline test/legacy-start-end.js]: done

**Comment by dominictarr** [comment]
Ah, this is definately something i'd fix in ltgt.

hmm, now that i look at it there is a bit of code seems to be duplicated or should live only in ltgt.
looking into this now...

**Comment by dominictarr** [comment]
merged into 6.5.1.
I tidied up after this, and updated ltgt, but your tests are in there. thanks for the PR!

**Comment by nolanlawson** [comment]
No prob! Happy to help; thanks for the great lib. :)
